[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.13.0"
nom = "7.1.3"
once_cell = "1.20.2"
regex = "1.11.1"
